-- 設備審計註冊摘要表
-- 用於追蹤每個設備在每個業務日期的累計交易計數和金額
-- 處理設備重啟後計數重置的情況

CREATE TABLE DEVICE_AR_SUMMARY (
    DEVICE_ID VARCHAR2(20 BYTE) NOT NULL,
    BE_ID NUMBER(10,0) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    AR_TYPE_IDENTIFIER VARCHAR2(20 BYTE) NOT NULL,
    CARD_MEDIA_TYPE_ID VARCHAR2(20 BYTE),
    TOTAL_COUNT NUMBER(19,0) NOT NULL,
    TOTAL_VALUE NUMBER(19,2),
    LAST_AR_SEQ_NUM NUMBER(10,0),
    LAST_UPDATED_TIME TIMESTAMP (6) WITH TIME ZONE NOT NULL,
    CREATED_TIME TIMESTAMP (6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_DEVICE_AR_SUMMARY PRIMARY KEY (DEVICE_ID, BE_ID, BUSINESS_DATE, AR_TYPE_IDENTIFIER, CARD_MEDIA_TYPE_ID)
);

-- 創建索引以提高查詢性能
CREATE INDEX IDX_DEVICE_AR_SUMMARY_DEVICE ON DEVICE_AR_SUMMARY(DEVICE_ID, BE_ID, BUSINESS_DATE);
CREATE INDEX IDX_DEVICE_AR_SUMMARY_DATE ON DEVICE_AR_SUMMARY(BUSINESS_DATE);

-- 添加註釋
COMMENT ON TABLE DEVICE_AR_SUMMARY IS '設備審計註冊摘要表，用於追蹤設備累計交易計數和金額，處理設備重啟後計數重置';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.DEVICE_ID IS '設備ID';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.BE_ID IS '業務實體ID';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.BUSINESS_DATE IS '業務日期';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.AR_TYPE_IDENTIFIER IS '審計註冊類型標識符';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.CARD_MEDIA_TYPE_ID IS '卡片媒體類型ID';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.TOTAL_COUNT IS '累計交易計數';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.TOTAL_VALUE IS '累計交易金額';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.LAST_AR_SEQ_NUM IS '最後處理的審計註冊序列號';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.LAST_UPDATED_TIME IS '最後更新時間';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.CREATED_TIME IS '創建時間';

