-- Device Audit Register Summary table
-- Used to track accumulated transaction count and amount for each device on each business date
-- Handles device restart count reset scenario

CREATE TABLE DEVICE_AR_SUMMARY (
    DEVICE_ID VARCHAR2(20 BYTE) NOT NULL,
    BE_ID NUMBER(10,0) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    AR_TYPE_IDENTIFIER VARCHAR2(20 BYTE) NOT NULL,
    CARD_MEDIA_TYPE_ID VARCHAR2(20 BYTE),
    TOTAL_COUNT NUMBER(19,0) NOT NULL,
    TOTAL_VALUE NUMBER(19,2),
    LAST_AR_SEQ_NUM NUMBER(10,0),
    LAST_UPDATED_TIME TIMESTAMP (6) WITH TIME ZONE NOT NULL,
    CREATED_TIME TIMESTAMP (6) WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_DEVICE_AR_SUMMARY PRIMARY KEY (DEVICE_ID, BE_ID, BUSINESS_DATE, AR_TYPE_IDENTIFIER, CARD_MEDIA_TYPE_ID)
);

-- Create indexes to improve query performance
CREATE INDEX IDX_DEVICE_AR_SUMMARY_DEVICE ON DEVICE_AR_SUMMARY(DEVICE_ID, BE_ID, BUSINESS_DATE);
CREATE INDEX IDX_DEVICE_AR_SUMMARY_DATE ON DEVICE_AR_SUMMARY(BUSINESS_DATE);

-- Add comments
COMMENT ON TABLE DEVICE_AR_SUMMARY IS 'Device Audit Register Summary table, used to track device accumulated transaction count and amount, handles device restart count reset';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.DEVICE_ID IS 'Device ID';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.BE_ID IS 'Business Entity ID';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.BUSINESS_DATE IS 'Business Date';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.AR_TYPE_IDENTIFIER IS 'Audit Register Type Identifier';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.CARD_MEDIA_TYPE_ID IS 'Card Media Type ID';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.TOTAL_COUNT IS 'Accumulated Transaction Count';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.TOTAL_VALUE IS 'Accumulated Transaction Amount';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.LAST_AR_SEQ_NUM IS 'Last Processed Audit Register Sequence Number';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.LAST_UPDATED_TIME IS 'Last Updated Time';
COMMENT ON COLUMN DEVICE_AR_SUMMARY.CREATED_TIME IS 'Created Time';

